<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="x-apple-disable-message-reformatting" />
      <meta name="apple-mobile-web-app-capable" content="yes" />
      <meta name="apple-mobile-web-app-status-bar-style" content="black" />
      <meta name="format-detection" content="telephone=no" />
      <title>Support Ticket</title>
   </head>
   <body>
       
     <br/><br/>
     <br/><br/>
        Dear {{$mailData['displayName']}},<br/><br/>
        
        <strong>Ticket ID:</strong> {{$mailData['ticketID']}} <br/>
        <strong>Subject:</strong> {{$mailData['subject']}} <br/>
        <strong>Department:</strong> {{$mailData['department']}} <br/>
        <strong>Query Type:</strong> {{$mailData['queryType']}} <br/>
        <strong>Priority:</strong> {{$mailData['priority']}} <br/>
        <strong>Generated By:</strong> {{$mailData['generatedBy']}} <br/>
        <strong>Generated On:</strong> {{$mailData['addedOn']}} <br/>

      <br/><br/><br/>
      Thanks & Regards,<br/>
      Team {{cmp()->companyName}}<br/><br/>
      <br/>
   </body>
</html>